name: test

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: dotfiles
      - name: Setup CI structure
        run: |
          # we need brew already upfront
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew --version
          # we need gnu sed to use the -i option properly without file extension
          brew install gnu-sed git
          # and add it to the path
          export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
          sed --version
          # we expect the file directory to be in $HOME
          mv dotfiles ~/.dotfiles
          # we allow the current user to change the shell without password prompt
          echo -e "$(whoami)\t\tALL = (ALL) NOPASSWD:$(which chsh)" | sudo tee -a /etc/sudoers
          # and test if it works without a password prompt
          sudo chsh -s $(which bash)
          # then replace the chsh for fish for the pipeline
          sed -i 's#chsh -s (which fish)#sudo chsh -s (which fish) (whoami)#' ~/.dotfiles/script/bootstrap.fish
          # ths will comment line 45-47 to brew cask with https as we do not have a ssh key for the pipeline
          sed -i '45s/^/#/' ~/.dotfiles/git/gitconfig.local.symlink 
          sed -i '46s/^/#/' ~/.dotfiles/git/gitconfig.local.symlink 
          sed -i '47s/^/#/' ~/.dotfiles/git/gitconfig.local.symlink 
          # we fake a git user.email to avoid a prompt
          git config --global user.name "test"
          git config --global user.email "test@example.com"
      - name: Install dotfiles from the README
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install fish grc
          cd ~/.dotfiles
          ./script/bootstrap.fish
      - name: Set macOS defaults
        run: |
          ~/.dotfiles/macos/set-defaults.sh
